server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookings-db
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  codec:
    max-in-memory-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# OpenFeign Configuration
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  circuitbreaker:
    enabled: true

# Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      flightService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    com.flightapp: DEBUG
